server:
  port:
    8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  # Use appropriate driver for your database type
    url: jdbc:mysql://localhost:3307/microservices # Replace with your database URL
    username: my_username
    password: my_password