server:
  port:
    8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Use appropriate driver for your database type
    url: jdbc:mysql://localhost:3306/microservices # Replace with your database URL
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect